### ISSUE TITLE
Support changed symlink

### ISSUE THREAD

**Issue by trotha01** [wking-io/elm-live#107]
The iosphere elm i18n tool works by changing a symlink, can we have elm-live reload when the symlink changes?

https://github.com/iosphere/elm-i18n

To Reproduce:
```
git clone git@github.com:iosphere/elm-i18n.git
npm install elm-i18n -g
cd elm-i18n/example
elm-i18n-switch -l En
elm-live
```

Then
```
elm-i18n-switch -l De --yes
```

Elm-live should re-compile after switching languages

**Comment by tomekwi** [comment]
Hey Trevor, thanks so much for the heads up about this. Sorry for the delay – I got super duper busy with life over the last weeks! Luckily, those time-consuming things are mostly over, so elm-live is back to life too.

Thanks a lot for the patience! I’ll get back to you asap 🙂

**Comment by trotha01** [comment]
Thanks for the update @tomekwi , np 👍

**Comment by tomekwi** [comment]
Hey @trotha01, that sounds like a useful thing to have! Two questions:

1. Does elm-i18n-switch change the file that the symlink points to? Or does it rewrite the symlink itself?
2. What’s the extension of the symlink and the file that the symlink points to?

**Comment by trotha01** [comment]
@wking-io I can go ahead and close. I'm not currently using elm-i18n or doing changes with symlinks. Thanks for following up.
