### ISSUE TITLE
Support for other budo command line args?

### ISSUE THREAD

**Issue by bitterjug** [wking-io/elm-live#114]
Our Elm app happens also to be a PWA with a service worker. 
I notice that Budo supports [SSL and HTTPS](https://github.com/mattdesl/budo/blob/master/docs/command-line-usage.md#ssl-and-https) and I wondered how easy it would be to pass through, e.g. the `--ssl` flag, `--cert` and `--key` options to the underlying server

**Comment by wking-io** [comment]
We no longer use budo so I am closing this PR. If you are very interested in these feature I would love to hear about it on: https://github.com/wking-io/elm-serve and we can bubble it up to here
