### ISSUE TITLE
forget to specify directory gives page "budo"

### ISSUE THREAD

**Issue by Saulzar** [wking-io/elm-live#118]
If I accidentally leave out the `--dir` in my elm-live command line it loads but gives me an empty page titled "budo"
e.g. 

`elm-live client/Main.elm --output html/elm.js --dir=html --open`

**Comment by wking-io** [comment]
Hey!

If you leave out the `--dir` option than it defaults to the current working directory. 

So you will need to make sure you are always passing in an option for that if your html file is located elsewhere. 

If that is how you are using it could you send me a link to the repo you are experiencing this problem on and we can get this figured out! 😊

**Comment by wking-io** [comment]
Budo is no longer used in elm-live if you face a similar problem with the new update please open a new issue
