### ISSUE TITLE
How to integrate with Phoenix Framework

### ISSUE THREAD

**Issue by sashaafm** [wking-io/elm-live#120]
Hello there, this may be a longshot but do you have documented how to integrate `elm-live` with Elixir's Framework?

Specially if one's serving the HTML via a Phoenix Template?

Thanks!

**Comment by sashaafm** [comment]
Hello @architectcodes, first of all congratulations on your new project and family.

Unfortunately I didn't find a way to do it. I may try again soon.

**Comment by wking-io** [comment]
Hey @sashaafm!

Based on my first intuition I am going to make a guess that the answer is no.

Unless you are just using Phoenix as an API and your Elm code as a SPA. 

However, if you are using Phoenix to render elm more as view templates then probably no. I would be interested to understand how you use Elm with Phoenix and maybe we can get a solid answer one way or the other!

**Comment by architectcodes** [comment]
#128 might be related

**Comment by sashaafm** [comment]
I haven't looked into this, but maybe this weekend if I have time I'll give a shot at removing `elm-brunch` from Phoenix and using `elm-live`

**Comment by sashaafm** [comment]
On this topic, I'll try to get it to work when `elm-live` is released for 0.19 and I migrate my app to it.

**Comment by wking-io** [comment]
@sashaafm sounds like @Razzeee's solution is the best way to integrate moving forward. I am going to close this issue if you do not feel the same feel free to open another issue and we can work something out!
