### ISSUE TITLE
Prevent page load if elm-test fails

### ISSUE THREAD

**Issue by milesfrain** [wking-io/elm-live#122]
I cannot detect when `elm-test` is failing without monitoring `elm-live` terminal output, and I usually keep this terminal minimized. I was hoping to see a 404, other error, or blank page. Current behavior reloads the previous `index.html`, even if tests are failing.
I believe I tried all combinations of `--before-build` `--after-build` and `--no-recover` options.
Best workaround so far is to pass this script to `--before-build` in order to produce a blank page upon test failure:
```
rm index.html
elm-test
```
I tried some other scripts to conditionally write error text to `index.html`, but this custom page is not picked-up by the browser without a manual refresh.

**Comment by architectcodes** [comment]
Hey @milesfrain, welcome to elm-live and thanks so much for reporting the issue!

If you’ve seen other issues or watched my twitter feed recently, you might notice how much is going on in my life right now. Not only with my full time startup job that’s right now more intensive than ever, but also [a business](https://homalive.com/) I’m building after hours – and a lovely little family that really deserves my time more than anything else 😊

Did you find a way around the issue in the end? I’ll be looking for new maintainers of elm-live – if you know anyone that’s keen to help solve the issue – or even take over the project in the longer run, please let me know! 🚀

I’d love to help here but realistically looking it might be pretty hard to get the proper focus time in the coming weeks.

**Comment by wking-io** [comment]
Hey @milesfrain! Just checking in on the status of this issue with you. I am taking over maintaining elm-live and am trying to do a little issue clean. I will close this issue if you are no longer dealing with this or not replying after a couple weeks. :)

**Comment by milesfrain** [comment]
I'd interpret this issue as a feature request, along with a workaround for others searching for this feature.
I am just using the workaround for now, but it would be great to see this feature included in elm-live.

**Comment by wking-io** [comment]
I do not think that this is something that I am going to look into for the foreseeable future myself, but if anyone else would like to take a stab feel free.
