### ISSUE TITLE
Watch elm.json and elm-package.json

### ISSUE THREAD

**Issue by architectcodes** [wking-io/elm-live#129]
When upgrading a codebase to Elm 0.19, I was making a lot of updates to `elm.json` (equivalent of the `elm-package.json` in Elm 0.18 and lower). It would be great if elm-live could kick off a rebuild when it notices that `elm.json` has changed.

If it also worked with https://github.com/architectcodes/elm-live/pull/119, it would all be pretty mind blowing!

**Comment by SupremumLimit** [comment]
Hi Will, I'd like to address this as well as #119 (especially #119). I see there was already a PR for #119 but it needs extra work now that we have elm.json in addition to elm-package.json. Are you happy for me to open a PR when I'm done? Anything I should take into consideration?

**Comment by wking-io** [comment]
Feel free to make a PR with what you think! I think that will be a great addition and shouldn't require any big architecture decisions so feel free to send what you got and we can review from there! 

Thanks for looking into this one!

**Comment by wking-io** [comment]
This was taken care of with PR #140!
