### ISSUE TITLE
Outdated elm-lang/elm-platform references

### ISSUE THREAD

**Issue by architectcodes** [wking-io/elm-live#131]
Hello again 👋 

I just noticed that one of the failure hints still refers to elm-plaftorm and points at the [elm-lang/elm-platform](https://git.io/elm-platform) repo:

https://github.com/wking-io/elm-live/blob/fb1f8e9041c347e0630aa017ba84ab48e3827cf9/source/elm-live.js#L122-L123

Hope it helps!

**Comment by wking-io** [comment]
Fixed!
