### ISSUE TITLE
Custom Index.html is overwritten

### ISSUE THREAD

**Issue by PascalLeMerrer** [wking-io/elm-live#133]
Hi

I just discovered elm-live
I tried it on a small apps with ports and flags
The content of the script node is replaced with the compiled app, so the glags and port calls are lost.
How can I get this working?

**Comment by wking-io** [comment]
You will need to make sure you pass the `--output=elm.js` option to elm-live. This gets passed to elm make and it will compile your Elm code to a js file you will include in your index.html

**Comment by PascalLeMerrer** [comment]
Works well, indeed. Thank you!

**Comment by Ploppz** [comment]
@wking-io I get this error when I try that

```
$ elm-live --output elm.js src/Main.elm


----------------------
|| ERROR IN COMMAND ||
----------------------


Usage: <elm-main> [options] [--] [elm make options]

-- Output In Wrong Location -----------------

You have used the elm make flag --output in the wrong location. As seen in the usage example about, all elm make flags must be added to your command after the -- separator.
```

**Comment by PascalLeMerrer** [comment]
Try 
```
elm-live src/Main.elm -- --output elm.js
````
Everything before -- is for elm live; everything after -- is passed to the elm compiler as parameters.

**Comment by Ploppz** [comment]
Yep that worked, thanks
