### ISSUE TITLE
Debug flag is not working

### ISSUE THREAD

**Issue by Maxim-Filimonov** [wking-io/elm-live#136]
Just installed 3.0.4 and noticed that debugging is not working anymore.
See [the video](https://app.blisk.io/screenRecords/shared/f22f29c0-bcaa-4d5e-97d6-97720d8419ca)

**Comment by Maxim-Filimonov** [comment]
Rolled back a bit and found that it only works in 3.0.1 for me.
3.0.2 gives me file not found :[

**Comment by Razzeee** [comment]
You need to do `elm-live src/Main.elm -- --debug`

**Comment by Maxim-Filimonov** [comment]
Oh, I see that's not very obvious. Also, I wonder why this change was made? 
I remember the `--` with npm drove me to using yarn

**Comment by Razzeee** [comment]
To quote Will King from the elm slack:
"Yeah, this keeps elm-live from being as tightly coupled to `elm make`. All options after `--` are passed into elm-make automatically. This way we do not have to manage code for all possible elm make options and if options are added, changed, or removed we do not have to release a new version."
