### ISSUE TITLE
Can no longer override the default port using --port

### ISSUE THREAD

**Issue by darrensiegel** [wking-io/elm-live#138]
I did some digging and this looks like it perhaps is a bug in commander related to specifying default values, but since it is preventing elm-live users from overriding the port, you may want to work around it.

If I do:
$ elm-live src/Main.elm --port=9000

I would expect elm-live to start and serve off of port 9000.  It does not, it serves off of the default 8000.

I've submitted PR #137 to address this. 

Thank you for building and maintaining this tool.

**Comment by wking-io** [comment]
Solved with PR #137
