### ISSUE TITLE
Error in 3.0.6 published version?

### ISSUE THREAD

**Issue by Skinney** [wking-io/elm-live#141]
I just tested out the 3.0.6 version of elm-live. According to the tag in git, it would seem that 3.0.6 includes the PR by alexkorban that watches files found in `elm.json`s source directories. However, when checking `node_modules/elm-live` it seems to be an older version.

So, either an older version of elm-live has been published under the 3.0.6 version, or the 3.0.6 tag is wrong?

**Comment by wking-io** [comment]
I have not fully tested the functionallity added by Alex. The 3.0.6 is for a `--pushstate` bug-fix. When I get done testing out the feature added by Alex I plan on releasing 3.1.0

**Comment by Skinney** [comment]
Ahh, ok. My bad :)

**Comment by wking-io** [comment]
Not a problem! Thanks for checking I very well could have forgot and that would have been a helpful reminder! 🙌😊
