### ISSUE TITLE
Change custom index.html to something other than index.html

### ISSUE THREAD

**Issue by DougVonMoser** [wking-io/elm-live#143]
I ran into this a couple times already. 
It seems problematic to have any custom html files (https://github.com/wking-io/elm-live#use-a-custom-html-file) share the file name that elm make will generate and subsequently overwrite. 

Perhaps custom.html can work to avoid any naming issues?

**Comment by wking-io** [comment]
I do not know if I follow.

**Comment by DougVonMoser** [comment]
Apologies. To be more clear:

elm-live is really neat in the sense that it supports both an html file or javascript file output from the elm make command. On top of that, when you direct elm-live to --output=elm.js, you're even able to reference your own style sheet and markup.  This is done by creating your own index.html file in the root of your project where you hook up elm.js in your html. 

In my opinion, this custom html file of index.html should simply have a different name. It seems weird to share a file name and directory with the index.html produced by a normal elm make command, or by running elm-live without the --output=elm.js. I've had my custom index.html blown away by running an elm make command and took me almost an hour to actually sort out what happened. 

If this is fine as is (maybe even a feature and not a bug), I just figure I'd log it as a troubleshooting step for anyone else who may run into this in the future. 

Thanks! Love the project!

**Comment by wking-io** [comment]
I think exposing the `startPage` option of elm-serve [here](https://github.com/wking-io/elm-serve#table-of-options-for-reload-opts-parameter) would solve the problem you are talking about! 😊

Would you be interested in making the PR for that @DougVonMoser?

**Comment by DougVonMoser** [comment]
ah neat. and you betcha!

**Comment by wking-io** [comment]
LookIng forward to your PR!

**Comment by DougVonMoser** [comment]
Awesome, thanks so much!
