### ISSUE TITLE
How to make elm-live ignore Emacs recovery and temp files

### ISSUE THREAD

**Issue by mattiasw2** [wking-io/elm-live#145]
Using elm-live 3.1.0 under Windows 10.  Use Emacs to edit file. I get 3 triggered changes for when I change one file. Since I use it under Windows, I list each individual file.

Is there anything I can do?

> elm-live src/MyStd.elm src/Texts.elm src/Main.elm src/MainModel.elm src/MainView.elm --pushstate --open --debug -- --output=../Lic6/wwwroot/elm.js

This is what is printed for a single change

```
elm-live:
  You’ve added `src\.#MainView.elm`. Rebuilding!

Success! Compiled 1 module.
Server restarted at 13:02:52

elm-live:
  You’ve changed `src\MainView.elm`. Rebuilding!

Success! Compiled 2 modules.

elm-live:
  You’ve removed `src\.#MainView.elm`. Rebuilding!

Success! Compiled 1 module.
Server restarted at 13:02:55
```

**Comment by lzrski** [comment]
Very similar issue happens with Elmjutsu (a plugin for Atom editor). It creates a temporary file at `src/ElmjutsuDumMyM0DuL3.elm` and deletes it immediately after building. This triggers Elm Live to build my code three times in short burst.

Perhaps Elm Live should have `--ignore` option?

**Comment by bpizzi** [comment]
> Perhaps Elm Live should have `--ignore` option?

Something like --ignore-hidden for not rebuilding after changes in a hidden file (ie. name starting with a dot) seems more idiomatic (and simple to implement) to me.

**Comment by tad-lispy** [comment]
@bpizzi

It wouldn't solve the Elmjutsu problem, would it?

**Comment by bpizzi** [comment]
@tad-lispy indeed not, but that would fix @mattiasw2's problem. 

The rational behind my remark was that hidden files are inherently tagged for being ignored (being, well, hidden), and implementing a corner case for ignoring files starting with a point seems like a quick fix, whereas a --ignore flag would be indeed a more powerful approach, but would need regexp or something like that, making it longer and more complicated to implement. 

Seeing that this issue has been opened for some times now, I guessed that perhaps @wking-io would be more keen to have a look at it if it was suggested to go with the quick fix first.

**Comment by wking-io** [comment]
Both of these issues are fixed! :) I was able to ignore them in the watcher and have no plans of adding an ignore flag for now, but if I start getting a lot of these requests I may think about it.
