### ISSUE TITLE
How to serve HTTPS?

### ISSUE THREAD

**Issue by rosensama** [wking-io/elm-live#155]
In Readme.md it says that using default settings pages will be available at https://localhost:8000, but I get http://localhost:8000.   Is there a way to use HTTPS?

Thanks.

**Comment by Munksgaard** [comment]
I don't think elm-live supports HTTPS directly. However, I've used [ngrok](https://ngrok.com/) successfully as a HTTPS proxy.

**Comment by rosensama** [comment]
So maybe just a simple documentation defect in Readme.md.

**Comment by Munksgaard** [comment]
I think so, but perhaps @wking-io can confirm.

**Comment by wking-io** [comment]
That is an mistake in the docs. That was available on the elm 0.18 version of elm-live, but I am looking into bringing that back!

**Comment by wking-io** [comment]
You can follow that feature here: https://github.com/wking-io/elm-serve/issues/4

**Comment by wking-io** [comment]
Just released HTTPS with v3.4.0. All you need to do is use the --ssl flag to turn it on :)
