### ISSUE TITLE
"cannot find module 'Browser'

### ISSUE THREAD

**Issue by stevensonmt** [wking-io/elm-live#156]
The error says elm-make failed. This suggests a need to change elm-live to the 0.19 syntax of `elm make` without the hyphen. The project builds fine with `elm make`.

**Comment by wking-io** [comment]
If you are getting and error that says `elm-make` then you have an older version of elm-live installed. Try removing it completely from your project as well as globally then re-installing it.

**Comment by stevensonmt** [comment]
I only have elm-live installed globally and `npm ls --global | grep elm` gives me `elm-live@3.4.0` which should be the latest version I think.

**Comment by wking-io** [comment]
Yeah someone else had that issue with their global install and they had to delete the package manually and re-install.
