### ISSUE TITLE
Support for urls with punctuation like "localhost:8000/24.3.2"

### ISSUE THREAD

**Issue by bstro** [wking-io/elm-live#159]
My app needs to support the ability for urls that have periods in them. As far as I can tell (from testing on my staging server), my app code does support it, but the server that elm-live runs gives me a response of `Cannot GET /24.3.2` which leads me to believe it is an issue with elm-live's server configuration. Is there anything I can do here?

**Comment by wking-io** [comment]
This should be fixed in the new alpha! You can check the README for how to install it.
