### ISSUE TITLE
Feature request: ability to pass init flags

### ISSUE THREAD

**Issue by stevensonmt** [wking-io/elm-live#160]
I may be missing something, but currently I see no way to output from elm-live a file that accounts for necessary init flags. For instance, I have a `Browser.element` app that needs the viewport dimensions upon loading. I can accomplish this by passing
```
    flags: {
        width: window.innerWidth,
        height: window.innerHeight
    }
```
into `var app = Elm.Main.init(...);`
But every time I edit any file the output file is overwritten, causing the loss of the flags. It would be nice to be able to do something like `elm-live src/main.elm -- --flags "width: window.innerWidth, height: window.innerHeight" --debug` and have the flags inserted automatically.

**Comment by wking-io** [comment]
You will need to set the `--output` flag and specify your output as a JS file as covered here in the elm documentation: https://guide.elm-lang.org/interop

Note: make sure you are passing the `--output` flag after -- in your elm-live command

**Comment by stevensonmt** [comment]
Okay, thanks. Changing output to JS file was the step I was missing.
