### ISSUE TITLE
--dir seems to disable --start-page

### ISSUE THREAD

**Issue by xilnocas** [wking-io/elm-live#161]
Hey @wking-io, thanks for taking over elm-live!

I'm on `elm-live --version == 3.4.0`

If I run this command

`elm-live src/Main.elm -p 8001 -s deploy/static/index.html  -- --output=dummy.js`

`localhost:8001/` serves index.html.

However, when running this

`elm-live src/Main.elm -p 8001 -s deploy/static/index.html -d deploy  -- --output=dummy.js`

`localhost:8001` serves `File Not Found`

I will try to come back through and provide a minimal directory setup that reproduces this, just wanted to get it on the issue tracker asap!

**Comment by wking-io** [comment]
Hey!

Could you try one thing for me! So, the -d flag tells `elm-serve` only the directory your index.html file is in and the -s should only need to be used if your html file has a custom name that is not index. Try:

```sh
elm-live src/Main.elm -p 8001 -d deploy/static -- --output=dummy.js
```

**Comment by xilnocas** [comment]
Interesting! Are you sure that's what `--dir` means? It seems to also try to serve requests for static assets _relative to the argument directory_, which is the behavior I want but was failing to get.

For example: I actually just finished getting my setup working by changing my directory structure a bit to this

```
deploy/
  - index.html
  - static/
   - foobar.css
   - baz.js
   - ...  
```

and then ran this from the directory that contains `deploy`

`elm-live src/Main.elm -p 8001 -d deploy/ -- --output=dummy.js`

WIth that running, the right `index.html` gets served at `/`, and when my app requests `/static/foobar.css` it gets `deploy/static/foobar.css` exactly like I want.  

By the same token, when I applied your suggestion to my old directory structure  (with `index.html` inside `static` along with everything else) `GET /` responed with `index.html`, but `GET /static/foobar.css` failed, because it was looking _inside the `static/` directory for another directory named `static`_

Maybe this isn't the intended behavior of `--dir`, but it's how my mental model of `elm-live` has worked for the past two years, and I never had any reason to believe it worked differently till now. 

Like I said, I've solved my immediate problem for the moment, but I'm happy to continue helping here if I can!

**Comment by wking-io** [comment]
Ahhh I was missing the context of your overall project structure! Yeah in that case you have the right mental model. 

So in your original example if you want `elm-serve` to pull assets the way you are describing but still be able to find the index.html file in a deeper folder you were only off one thing! The -s flag is relative to the -d flag. So you could tweak the original to be:

```sh
elm-live src/Main.elm -p 8001 -s static/index.html -d deploy -- --output=dummy.js
```

**Comment by xilnocas** [comment]
Beautiful! I'll go ahead and close. Thanks for the help!!
