### ISSUE TITLE
Html not looking for the correct relative css/js paths

### ISSUE THREAD

**Issue by mikederksen** [wking-io/elm-live#162]
# Situation
I have the following file structure:
```
- package.json
- elm.json
- src
    - Main.elm
   - etc.
- web
   - application.html
   - application.css
   - main.js (Generated by elm-live) 
```

The `application.html` is the file in which the generated elm javascript is included. `main.js` is the javascript that is generated by `elm-live`. The package.json contains the following 'watch' script:
`elm-live -p 3002 --start-page=web/application.html src/Main.elm -- --output=web/main.js`

In the `application.html` the includes are as following:
```html
<link rel="stylesheet" href="./application.css">
<script src="./main.js"></script>
```

# Behavior
I would expect that the html file is able to successfully load the css and js files. Insteda it gives an error that it is not able to find both the css and js files. To be able to find those files I have to change the html includes to the following:
```html
<link rel="stylesheet" href="./web/application.css">
<script src="./web/main.js"></script>
```

This indicates that the html file is searching from the directory in which `elm-live` is called and not from the actual directory in which the html file is placed, which is very confusing and not normal html-behavior.

# Versions
- Node: v11.9.0
- Elm: 0.19.0
- Elm-live: 3.4.0
- OS: MacOs 10.14.1

**Comment by wking-io** [comment]
Hey! So the only thing you are missing is the --dir flag. This tells the server where to serve the root of your application from. So your command will look like this:

```
elm-live src/Main.elm -p 3002 --start-page=web/application.html --dir=web -- --output=web/main.js
```

**Comment by mikederksen** [comment]
Thanks! Running this made my browser to not be able to find some localhost file. By making a slight variation of your command I was able to run it successfully:

```
elm-live src/Main.elm -p 3002 --start-page=application.html --dir=web -- --output=web/main.js
```
