### ISSUE TITLE
Corrupt binary

### ISSUE THREAD

**Issue by mksmtn** [wking-io/elm-live#164]
Hi! Thanks for a great tool. There is a minor issue I'm facing. It happens very rarely, but just to let you know it exists. After I've made a change, `elm-live` says something like

```
CORRUPT BINARY - path/to/project/elm/elm-stuff/0.19.0/Pages-Protein-View.elmo

The binary data at
 path/to/project/elm/elm-stuff/0.19.0/Pages-Protein-View.elmo is
corrupt.

```

Then I just stop `elm-live`, start it again and everything is working fine.

 I'm on 
- node v8.10.0
- elm 0.19.0
- Ubuntu 18.04.2 LTS
- Visual Studio Code 1.32.3

**Comment by wking-io** [comment]
Thank you for shooting this issue my way! Hopefully we can get this figured out. At least restarting fixes the issue, but hopefully I can find a fix so you do not have to do that :)

**Comment by wking-io** [comment]
Question: Did you try deleting your elm-stuff folder and and re-installing?

**Comment by mksmtn** [comment]
I've just deleted it, so I'll report if the issue happens again

**Comment by lucarakuten** [comment]
This could be a race condition with other script that compile elm, for example IDE plugins

**Comment by wking-io** [comment]
Oh that is a good point.

**Comment by lucamug** [comment]
I did some testing using this snippet to monitor the elm-stuff folder:

```
const chokidar = require('chokidar');
chokidar.watch('elm-stuff', {ignored: /(^|[\/\\])\../}).on('all', (event, path) => {
  console.log(event, path);
});
```

Saving a file (I use Atom IDE) or compiling both result in:

```
change elm-stuff/0.19.0/Main.elmo
change elm-stuff/0.19.0/Main.elmi
```

when elm-live is running, I get something like:

```
change elm-stuff/0.19.0/Main.elmi
change elm-stuff/0.19.0/Main.elmi
change elm-stuff/0.19.0/Main.elmo
change elm-stuff/0.19.0/Main.elmi
change elm-stuff/0.19.0/Main.elmo
```

..I am actually surprised not to get some issue all the time

**Comment by mksmtn** [comment]
Well, I have not encountered this issue again. I guess I tried to use docker-compose for elm-live, and after facing the issue I gave it up. So maybe it should be closed?

**Comment by wking-io** [comment]
Okay I will close for now, but let me know if it happens again!
