### ISSUE TITLE
elm-live taking 70% of CPU also when idle

### ISSUE THREAD

**Issue by lucamug** [wking-io/elm-live#167]
Recently I am getting the problem of elm-live getting around 70% of CPU resources also when is doing nothing.

I have the same issue on two macs. This problem appear around one month ago.

MacBook Pro - OS El Capitan
Node v.7.6.0
elm-live v.3.4.0

<img width="608" alt="Screen Shot 2019-05-12 at 10 16 01" src="https://user-images.githubusercontent.com/5551094/57576639-a518d180-749f-11e9-81f6-c9558546dd4b.png">

**Comment by wking-io** [comment]
Hey! I merged your PR and tested everything and it looked good! Thank you so much for looking into this and figuring out what was going on. :)
