### ISSUE TITLE
Watch pattern issue?

### ISSUE THREAD

**Issue by YuukanOO** [wking-io/elm-live#170]
Hi there! I'm currently trying Elm and find this nice project so thanks!

Just one question, I have just created a new project with `elm init` so my directory structure looks like this:

```
│   elm.json
│
└───src
        Main.elm
```

When running `elm-live src\Main.elm --open` in the root directory, only files in `src\**\*.elm` are watched for changes so whenever I change the `Main.elm` nothing happened (I'm on Windows). Shouldn't the watch pattern also include the `src\*.elm` stuff?

**Comment by harrysarson** [comment]
The glob `src\**\*.elm` should include files with paths like `src\Main.elm` (the `**` pattern matches zero or more directories).

I have a suspicion that #168 has broken this - does watching work correctly if you use elm-live v3.4.0 (instead of v3.4.1)?

**Comment by YuukanOO** [comment]
You were right! It works fine in `v3.4.0` :/

**Comment by lucamug** [comment]
@YuukanOO, do you specify the dir that elm-live server should watch ("The base for static content")?

Which are the arguments that you use to run elm-live?

**Comment by YuukanOO** [comment]
@lucamug I use the command `elm-live src\Main.elm --open`

**Comment by lucamug** [comment]
@YuukanOO I tried your same configuration and it seems working on Mac. There will be a new version of elm-ui soon and this part will also be impacted so I would suggest you to stay on `3.4.0` for the time being until the new version is out

**Comment by YuukanOO** [comment]
No problem! I guess it's specific to windows then, I'll try in Linux.

**Comment by harrysarson** [comment]
A patch release should break something like this though

**Comment by wking-io** [comment]
Hey! Sorry for the delay. I have been working on a new version of elm-live with @lucamug and as of last week I am a Father soooo things have been a little busy. :) I will try and look into why this is happening on Windows and make sure this is not happening in the new release

**Comment by harrysarson** [comment]
Congratulations 🎊

**Comment by YuukanOO** [comment]
@wking-io No problems, at least there is a workaround for now ;) And congrats to you! :champagne:

**Comment by wking-io** [comment]
Okay so figured out what is going on. This has actually been happening for awhile and has to do with the chokidar issue here: https://github.com/paulmillr/chokidar/issues/777

It doesn't have to do with any changes we made, but the fix I believe will be to pass the `cwd` option instead of using `path.join` passing the full dir path.

**Comment by YuukanOO** [comment]
@wking-io Will try and make a PR!

**Comment by YuukanOO** [comment]
Actually, it is easier to replace `\` to `/` in the `getSourceDirs` method since multiple directories can be specified by the user. I know this is an uglifier fix but it works fine and shouldn't cause any issue in the future and could be removed safely when the chokidar issue will be resolved. What do you think?

**Comment by wking-io** [comment]
If you can confirm that doing that solves the problem on Windows then that works for me! Make a PR and I will confirm it works on Mac and we can call it a day :)

**Comment by wking-io** [comment]
This should be fixed in the new alpha! You can check the README for how to install it.
