### ISSUE TITLE
refresh page infinity *alpha

### ISSUE THREAD

**Issue by justgook** [wking-io/elm-live#176]
create
```elm
module Main exposing (..)
import Html
main = Html.text "hello"
```
run `elm-live ./src/Main.elm`

first run will refresh page infinity, until changes in any of files

**Comment by wking-io** [comment]
That is because that is an invalid elm program. If you just open the output from running `elm make` on the same file it will show a console error and be broken.

**Comment by justgook** [comment]
https://ellie-app.com/6bJTRHfKDHSa1

**Comment by justgook** [comment]
BTW - same result i getting for other apps too (that is 15k LoC big, with start point of Browser.application)

**Comment by wking-io** [comment]
Hmmm interesting! Thanks for the more in depth example! I will look into that. Thanks for testing out the alpha for me too! Means a lot to get all of the help :)

**Comment by hanneskaeufler** [comment]
Seeing infinite refresh as well on my app, until I change the elm file at least once.

**Comment by wking-io** [comment]
Fixed in most recent release!
