### ISSUE TITLE
elm-live 4.0.0 crashes on ubuntu 18.04

### ISSUE THREAD

**Issue by sFaurite** [wking-io/elm-live#186]
Hi, Thanks for the hard work.

The new 4.0 version seems not to work for me, it crashes with :

events.js:239
    throw new TypeError('"listener" argument must be a function');
    ^

TypeError: "listener" argument must be a function
    at _addListener (events.js:239:11)
    at Server.addListener (events.js:297:10)
    at new Server (_http_server.js:269:10)
    at Object.createServer (http.js:34:10)
    at model (/tmp/elm-live/node_modules/elm-live/lib/src/start.js:255:75)
    at /tmp/elm-live/node_modules/crocks/core/compose.js:8:14
    at settle (/tmp/elm-live/node_modules/crocks/Async/index.js:151:16)
    at /tmp/elm-live/node_modules/crocks/Async/index.js:27:62
    at fork (/tmp/elm-live/node_modules/crocks/Async/index.js:155:20)
    at /tmp/elm-live/node_modules/crocks/Async/index.js:224:16

elm-live@4.0.0
Ubuntu 18.04.3 LTS
node v8.10.0

I have probably installed something wrong.
I tried either : 
npm install elm-live 
and 
npm install -g elm-live

Any idea ?

**Comment by Bernardoow** [comment]
Same here with elm-live 4.0.0

I using v8.10.0.

"elm-live": "3.4.1" works ok.

**Comment by wking-io** [comment]
The current version of elm-live only supports the LTS version of node (v10) and up. I made that decision since v8 will be unsupported the end of this year.

Are you able to bump your node version up or are you locked in to v8?

**Comment by Bernardoow** [comment]
Hi @wking-io !

It's ok to me to update the node version. 

I suggest you to improve the readme because I skip the information about 0.18 so I skipped the information about node 10.. I think you should move this information some lines up.

**Comment by sFaurite** [comment]
OK perfect, I upgraded to Node v10 and it works like a charm.

Thanks.
