### ISSUE TITLE
--hot blanks the page after a manual reload

### ISSUE THREAD

**Issue by Darker7** [wking-io/elm-live#211]
If I load a file using --hot and manually reload the page then I get an empty page.

elm-live --version: 4.0.1  
Browser: Opera (v66.0.3515.27)  
OS: Linux Mint 19.2 Tina

**Comment by lucamug** [comment]
@Darker7 , do you get any error in the console?

I am having similar issue and I am getting the error
```
elm.js:37126 Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at findNavKey (elm.js:37126)
    at hookedInit (elm.js:37218)
    at _Platform_initialize (elm.js:1978)
    at _Platform_initialize (elm.js:37256)
    at elm.js:4093
    at elm.js:20
    at Object.module.init (elm.js:36980)
    at index-hot.html:29
```

<img width="595" alt="Screen Shot 2020-01-31 at 9 34 30" src="https://user-images.githubusercontent.com/5551094/73502646-01949600-440d-11ea-97c8-d9aaa2c74af5.png">

<img width="826" alt="Screen Shot 2020-01-31 at 9 34 47" src="https://user-images.githubusercontent.com/5551094/73502656-06594a00-440d-11ea-888b-fc5cee237c15.png">

**Comment by codesections** [comment]
I have also encountered this issue.  I do not get the `hasOwnProperty` error in the JavaScript console; instead, I get 

```js
Uncaught (in promise) TypeError: myDisposeCallback is not a function
```

**Comment by klazuka** [comment]
@wking-io can you update elm-hot in your `package.json` to version 1.1.4 (or relax the constraint to include patch releases)? See https://github.com/klazuka/elm-hot/issues/40#issuecomment-584672342

**Comment by lucamug** [comment]
This issue can be close, it has been fixed.

Thank you @klazuka and @wking-io
