### ISSUE TITLE
elm-live returns nothing when running in a docker container

### ISSUE THREAD

**Issue by dbj** [wking-io/elm-live#224]
## Setup
* elm-live 4.0.1
* Site image built from the node:13.12.0-buster-slim image
* Docker run maps host port 8000 to container port 8000
* Container runs and executes: `elm-live ./src/Main.elm --dir=./static --pushstate -o -- --output=./static/assets/js/elmsite.js --debug`

## Reproduce
* Connect from the host : http://localhost:8000 and literally nothing is returned from the server

## Expected Results
* Connect from the host : http://localhost:8000 and and the index.html file in the ./static directory is returned

## Testing
* When I open a bash shell on the running container and connect to port 8000 using curl, the index.html file in the ./static directory is returned, so I know elm-live is configured and running properly

**Comment by dcellucci** [comment]
I found that adding `--host=0.0.0.0` to the elm-live options (before the `--`) fixed this for me.

**Comment by asett0** [comment]
Correct me if my terminology is wrong. Docker assigns dynamic IP addresses to its containers. Because of this you need to specify `--host=0.0.0.0`. `0.0.0.0` is essentially an alias to listen on all IP addresses.

**Comment by dbj** [comment]
Of course. Thank you for pointing that out. :).
