### ISSUE TITLE
Error in console using hot-reload

### ISSUE THREAD

**Issue by lucamug** [wking-io/elm-live#225]
Is it only me that is getting this error?

"main-with-debugger.js:65597 Uncaught ReferenceError: module is not defined"

<img width="602" alt="Screen Shot 2020-04-06 at 13 44 22" src="https://user-images.githubusercontent.com/5551094/78523846-1296c480-780d-11ea-81fc-5aec1886649f.png">

<img width="472" alt="Screen Shot 2020-04-06 at 13 44 41" src="https://user-images.githubusercontent.com/5551094/78523853-162a4b80-780d-11ea-80bc-6433748ef39d.png">

`module` is defined in `elm-live/lib/src/websocket.js`:

```

// The following 20 lines are from https://github.com/klazuka/elm-hot/blob/master/test/client.js#L40
var myDisposeCallback = null

// simulate the HMR api exposed by webpack
var module = {
  hot: {
    accept: function () {},

    dispose: function (callback) {
      myDisposeCallback = callback
    },

    data: null,

    apply: function () {
      var newData = {}
      myDisposeCallback(newData)
      module.hot.data = newData
    }

  }
};
```
I don't remember how this was injected in the Elm code... maybe there is an issue there?
I felt this was working few days ago, so maybe is only me that screwed something...

**Comment by lucamug** [comment]
I eventually found that this issue is coming from this other issue (https://github.com/wking-io/elm-live/issues/220) that I opened in the past. When my index.html has parameters, the automatic reload stop working...

**Comment by kraklin** [comment]
I ran into this issue right now without having any query parameters, I have just turn on the hot reloading on simple one Elm file app :(

**Comment by kraklin** [comment]
If I start `elm-live` with `--open` parameter it works, only when I manually reload the page I cannot see any of the page content.

**Comment by mrbalov** [comment]
I also had a similar issue setting up routing. Appeared that the problem was in relative paths in the `index.html`. So, I changed
```html
<script type="text/javascript" src="./index.js"></script>
```
to
```html
<script type="text/javascript" src="/index.js"></script>
```
and it solved my problem. Hope this will help you.
