### ISSUE TITLE
file watcher does not work on mounted docker volumes

### ISSUE THREAD

**Issue by Odalrick** [wking-io/elm-live#247]
This isn't a bug in elm-live, rather an unfortunate side effect of how docker works.

However I'm hoping there is an option to use polling for file watching that could be implemented quickly just by adding a command line option along the lines of nodemon: https://www.npmjs.com/package/nodemon#application-isnt-restarting

**Comment by Odalrick** [comment]
I finally had some time to look at this and found two things: it _was_ as easy to fix as I hoped it would be; and my original problem was me writing the wrong paths. Docker works fine with file watching.

Regardless the option to use polling might be useful for someone else and here is a pull request. #249

**Comment by wking-io** [comment]
I think I will leave this until someone else has this issue. It is intended to only be a development tool locally and want to keep features and flags from bloat unless there are a large number of necessary use cases.
