### ISSUE TITLE
Prepublish hook is not executable without `sh`

### ISSUE THREAD

**Issue by peacememories** [wking-io/elm-live#69]
While testing code for `elm-live` I've noticed publishing (or in this case `npm link`-ing) the repository on Windows fails because the prepublish hook is written in shellscript.
One way around this would be to use something like shelljs and port the script to a javascript file.

**Comment by tomekwi** [comment]
Yeah, well to be honest the prepublish hook also uses `man` to compile the help. So it’s very unlikely we can get it to run natively on Windows.

So far we’ve been getting around this by only releasing from a Unix computer. Releasing from a CI server instead seems to be the way to go – if anyone wants to help, we’ll very much appreciate it!

**Comment by wking-io** [comment]
I think a good solution for this would be to start transitioning Elm-live to a command-line tool like commander. It will help with argument management and remove the need for man to run during prepublish

**Comment by wking-io** [comment]
Issue should be resolved now. However, if that is not the case please open a new issue and we can get it figured out.
