### ISSUE TITLE
Possible to live rebuild more than 1 Elm file?

### ISSUE THREAD

**Issue by samueller** [wking-io/elm-live#89]
I have different `.elm` files that correspond to different webpages. As an example, I might have an `Index.elm` file that gets compiled and referenced in `index.html` and I have a `Dashboard.elm` file for `dashboard.html`. I run `elm-live` with:
```
elm-live Index.elm --output=public/elm/index.js --open
```
Works great for `Index.elm`, but changes to `Dashboard.elm` do not get recompiled. Is there a way to have both files auto-rebuild?

**Comment by tomekwi** [comment]
Good question! I don’t think it’s possible at the moment. Can you suggest a reasonable API for this? Keep in mind that elm-live is intentionally a very slim wrapper over elm-make, so `elm-live Index.elm --output=public/elm/index.js` is _almost_ the same as `elm-make Index.elm --output=public/elm/index.js`. This allows us to be very intuitive and future-proof. For example, when Elm 0.18 came out, we were able to support `--debug` instantly. No changes to elm-live needed. 😀

Don’t get me wrong though. I totally see your use case, just thinking about a reasonable and intuitive API to get this kind of behavior.

**Comment by samueller** [comment]
Makes sense for elm-live to be a slim wrapper over elm-make. One option is to run elm-live with a list of `.elm` and output `.js` file pairs:
```
elm-live Index.elm --output=public/elm/index.js Dashboard.elm --output=public/elm/dashboard.js --open
```
Any `.elm` file changes and *both* `Index.elm` **and** `Dashboard.elm` get recompiled with the corresponding elm-make commands. Hopefully, elm-make is able to recognize not to compile when the dependent `.elm` files have an earlier timestamp than the target?

**Comment by tomekwi** [comment]
Looks good! Intuitive and unambiguous, at first sight.

> Hopefully, elm-make is able to recognize not to compile when the dependent .elm files have an earlier timestamp than the target?

I don’t think that’s the case. With the current design of elm-live and elm-make, this would probably mean recompiling both files every time an `.elm` file changes.

On a positive note though, elm-make is smart enough to precompile modules and use the precompiled version if there were no changes to the source file in the meantime. So although elm-make _would_ recompile both files, one of those recompilations would be super cheap.

**Comment by tomekwi** [comment]
To be totally honest with you, there’s a lot happening in my life right now and I likely won’t be able to pick this up very soon. elm-live is a [very open](https://github.com/tomekwi/elm-live/pulls?utf8=%E2%9C%93&q=is%3Apr%20-author%3Agreenkeeperio-bot%20) project though, so you’re more than welcome to contribute! I always find the time for reviewing stuff 🙂

**Comment by Natim** [comment]
Why don't you add a package.json rule like that:

``"live": "elm-live Index.elm --output=public/elm/index.js --open && elm-live Dashboard.elm --output=public/elm/dashboard.js --open`` ?

**Comment by tomekwi** [comment]
For the time being, there’s a cheeky npm module making it nice and easy to run two commands in parallel: https://www.npmjs.com/package/concurrently.

**Comment by wking-io** [comment]
Hmm this is interesting. I will think about this. I think the answer here is to move outside of the CLI in a more complex use case like this.

**Comment by wking-io** [comment]
The way that elm compiler handles two separate elm sources is still as one output so as this is just a live server on top of elm make I do not think we will be adding this ability to have multiple outputs. However you can already have multiple input files. To see how you can checkout the doc site at https://elm-live.com

**Comment by shamansir** [comment]
Would also be useful for testing libraries wrapped in `Platform.worker`, where the test or example itself is Elm application and Worker is another Web Application with no view.

**Comment by mihkell** [comment]
I have a long running process in Platform.worker. So would be nice, if I could add those to elm-live watch list as well.
